title: "QuREX Documentation"
author: "Riccardo Reho"
sphinx:
sphinx:
  config:
    bibtex_reference_style: author_year

bibtex_bibfiles:
  - references.bib  # Make sure this points to your .bib file for citations
