title: "QuREX Documentation"
author: "Riccardo Reho"
sphinx:
  config:
    bibtex_reference_style: author_year
  extra_extensions:
    - sphinx_proof
#parse:
#   myst_enable_extensions:
#   - amsmath

bibtex_bibfiles:
  - references.bib  # Make sure this points to your .bib file for citations
