title: "QuREX Documentation"
author: "Riccardo Reho"

sphinx:
  config:
    bibtex_reference_style: author_year

    # Enable equation numbering and styling like LaTeX
    mathjax3_config:
      tex:
        tags: "none"            # Number all displayed equations
        tagSide: "right"       # Equation numbers on the right
        tagIndent: "0.8em"     # Spacing before equation numbers

    # Enable MyST extensions for advanced math and referencing
    myst_enable_extensions:
      - amsmath               # Enables environments like align, gather
      - dollarmath            # Inline and block LaTeX with $...$ or $$...$$
      - deflist               # (Optional) Definition lists
      - linkify               # Auto-detect links
      - substitution          # Enable |substitution| syntax (fixed name)
      - colon_fence           # For ::: fenced blocks (like admonitions)
      - smartquotes           # Typographic quotes

  extra_extensions:
    - sphinxcontrib.bibtex    # For citations and references

bibtex_bibfiles:
  - references.bib            # Your BibTeX file
